import type { DashboardStats, ActivityTrend } from '@/types'

export const mockDashboardStats: DashboardStats = {
  totalEvents: 12,
  activeVolunteers: 14,
  totalHours: 580,
  ongoingProjects: 3,
}

export const mockActivityTrends: ActivityTrend[] = [
  {
    month: 'Jan',
    monthNumber: 1,
    yearNumber: 2025,
    eventsCount: 1,
    volunteersCount: 8,
    hoursSum: 48,
  },
  {
    month: 'Feb',
    monthNumber: 2,
    yearNumber: 2025,
    eventsCount: 1,
    volunteersCount: 12,
    hoursSum: 72,
  },
  {
    month: 'Mar',
    monthNumber: 3,
    yearNumber: 2025,
    eventsCount: 1,
    volunteersCount: 15,
    hoursSum: 60,
  },
  {
    month: 'Apr',
    monthNumber: 4,
    yearNumber: 2025,
    eventsCount: 1,
    volunteersCount: 20,
    hoursSum: 100,
  },
  {
    month: 'May',
    monthNumber: 5,
    yearNumber: 2025,
    eventsCount: 1,
    volunteersCount: 10,
    hoursSum: 50,
  },
  {
    month: 'Jun',
    monthNumber: 6,
    yearNumber: 2025,
    eventsCount: 1,
    volunteersCount: 25,
    hoursSum: 140,
  },
  {
    month: 'Jul',
    monthNumber: 7,
    yearNumber: 2025,
    eventsCount: 1,
    volunteersCount: 8,
    hoursSum: 32,
  },
  {
    month: 'Aug',
    monthNumber: 8,
    yearNumber: 2025,
    eventsCount: 0,
    volunteersCount: 0,
    hoursSum: 0,
  },
  {
    month: 'Sep',
    monthNumber: 9,
    yearNumber: 2025,
    eventsCount: 1,
    volunteersCount: 18,
    hoursSum: 90,
  },
  {
    month: 'Oct',
    monthNumber: 10,
    yearNumber: 2025,
    eventsCount: 0,
    volunteersCount: 0,
    hoursSum: 0,
  },
  {
    month: 'Nov',
    monthNumber: 11,
    yearNumber: 2025,
    eventsCount: 1,
    volunteersCount: 14,
    hoursSum: 56,
  },
  {
    month: 'Dec',
    monthNumber: 12,
    yearNumber: 2025,
    eventsCount: 1,
    volunteersCount: 10,
    hoursSum: 60,
  },
]
