import type { Event, EventWithStats } from '@/types'
import { mockCategories } from './categories'

const base: Event[] = [
  {
    id: 'e1',
    eventName: 'Village Cleanliness Drive',
    description: 'Community cleaning in adopted village',
    eventDate: '2025-02-20',
    startTime: '08:00',
    endTime: '14:00',
    location: 'Wagholi Village',
    maxParticipants: 50,
    eventStatus: 'completed',
    hoursCredits: 6,
    categoryId: 1,
    createdBy: 'v1',
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-02-21'),
  },
  {
    id: 'e2',
    eventName: 'Blood Donation Camp',
    description: 'Annual blood donation drive on campus',
    eventDate: '2025-03-10',
    startTime: '09:00',
    endTime: '16:00',
    location: 'College Auditorium',
    maxParticipants: 100,
    eventStatus: 'completed',
    hoursCredits: 4,
    categoryId: 5,
    createdBy: 'v1',
    createdAt: new Date('2025-02-01'),
    updatedAt: new Date('2025-03-11'),
  },
  {
    id: 'e3',
    eventName: 'Tree Plantation Drive',
    description: 'Plant 500 trees in campus and surroundings',
    eventDate: '2025-04-22',
    startTime: '07:00',
    endTime: '12:00',
    location: 'College Campus',
    maxParticipants: 80,
    eventStatus: 'completed',
    hoursCredits: 5,
    categoryId: 6,
    createdBy: 'v3',
    createdAt: new Date('2025-03-15'),
    updatedAt: new Date('2025-04-23'),
  },
  {
    id: 'e4',
    eventName: 'First Aid Workshop',
    description: 'Basic first aid and emergency response training',
    eventDate: '2025-05-15',
    startTime: '10:00',
    endTime: '15:00',
    location: 'Seminar Hall',
    maxParticipants: 60,
    eventStatus: 'completed',
    hoursCredits: 5,
    categoryId: 4,
    createdBy: 'v1',
    createdAt: new Date('2025-04-20'),
    updatedAt: new Date('2025-05-16'),
  },
  {
    id: 'e5',
    eventName: 'NSS Special Camp',
    description: '7-day residential camp for community development',
    eventDate: '2025-06-01',
    startTime: '06:00',
    endTime: '20:00',
    location: 'Kamshet Village',
    maxParticipants: 40,
    eventStatus: 'completed',
    hoursCredits: 56,
    categoryId: 3,
    createdBy: 'v1',
    createdAt: new Date('2025-05-01'),
    updatedAt: new Date('2025-06-08'),
  },
  {
    id: 'e6',
    eventName: 'Digital Literacy Program',
    description: 'Teaching basic computer skills to villagers',
    eventDate: '2025-07-20',
    startTime: '09:00',
    endTime: '13:00',
    location: 'Wagholi Community Hall',
    maxParticipants: 30,
    eventStatus: 'completed',
    hoursCredits: 4,
    categoryId: 1,
    createdBy: 'v5',
    createdAt: new Date('2025-06-15'),
    updatedAt: new Date('2025-07-21'),
  },
  {
    id: 'e7',
    eventName: 'College Cultural Fest Service',
    description: 'NSS volunteer service during college fest',
    eventDate: '2025-09-15',
    startTime: '08:00',
    endTime: '18:00',
    location: 'College Campus',
    maxParticipants: 70,
    eventStatus: 'completed',
    hoursCredits: 10,
    categoryId: 2,
    createdBy: 'v1',
    createdAt: new Date('2025-08-20'),
    updatedAt: new Date('2025-09-16'),
  },
  {
    id: 'e8',
    eventName: 'Road Safety Awareness Rally',
    description: 'Awareness drive on road safety',
    eventDate: '2025-11-10',
    startTime: '08:00',
    endTime: '12:00',
    location: 'City Center',
    maxParticipants: 60,
    eventStatus: 'ongoing',
    hoursCredits: 4,
    categoryId: 1,
    createdBy: 'v3',
    createdAt: new Date('2025-10-15'),
    updatedAt: new Date('2025-11-01'),
  },
  {
    id: 'e9',
    eventName: 'Health Check-up Camp',
    description: 'Free health screening for underprivileged',
    eventDate: '2025-12-05',
    startTime: '09:00',
    endTime: '15:00',
    location: 'Government Hospital',
    maxParticipants: 45,
    eventStatus: 'registration_open',
    hoursCredits: 6,
    categoryId: 1,
    createdBy: 'v1',
    createdAt: new Date('2025-11-01'),
    updatedAt: new Date('2025-11-20'),
  },
  {
    id: 'e10',
    eventName: 'Environment Workshop',
    description: 'Workshop on sustainability and waste management',
    eventDate: '2026-01-15',
    startTime: '10:00',
    endTime: '14:00',
    location: 'Seminar Hall B',
    maxParticipants: 50,
    eventStatus: 'registration_open',
    hoursCredits: 4,
    categoryId: 4,
    createdBy: 'v5',
    createdAt: new Date('2025-12-10'),
    updatedAt: new Date('2026-01-05'),
  },
  {
    id: 'e11',
    eventName: 'Republic Day Parade',
    description: 'NSS unit participation in Republic Day celebrations',
    eventDate: '2026-01-26',
    startTime: '07:00',
    endTime: '11:00',
    location: 'City Parade Ground',
    maxParticipants: 40,
    eventStatus: 'upcoming',
    hoursCredits: 4,
    categoryId: 2,
    createdBy: 'v1',
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-01-10'),
  },
  {
    id: 'e12',
    eventName: 'Coding for Social Good',
    description: 'Hackathon to build apps for NGOs',
    eventDate: '2026-02-28',
    startTime: '09:00',
    endTime: '18:00',
    location: 'Computer Lab',
    maxParticipants: 35,
    eventStatus: 'planned',
    hoursCredits: 8,
    categoryId: 4,
    createdBy: 'v5',
    createdAt: new Date('2026-01-20'),
    updatedAt: new Date('2026-02-01'),
  },
]

export const mockEvents: Event[] = base

export const mockEventsWithStats: EventWithStats[] = base.map((e) => {
  const cat = mockCategories.find((c) => c.id === e.categoryId)
  return {
    ...e,
    category: cat ?? null,
    categoryName: cat?.categoryName ?? null,
    categoryColor: cat?.colorHex ?? null,
    participantCount: Math.floor(Math.random() * (e.maxParticipants ?? 50)) + 5,
    totalHours: Math.floor(Math.random() * 200) + 20,
  }
})
