import type {
  EventParticipation,
  EventParticipationWithVolunteer,
  EventParticipationWithEvent,
} from '@/types'
import { mockVolunteers } from './volunteers'
import { mockEvents } from './events'

export const mockParticipations: EventParticipation[] = [
  {
    id: 'p1',
    eventId: 'e1',
    volunteerId: 'v1',
    participationStatus: 'present',
    hoursAttended: 6,
    approvalStatus: 'approved',
    approvedBy: 'v1',
    approvedAt: new Date('2025-02-22'),
    feedback: null,
    registeredAt: new Date('2025-01-20'),
    updatedAt: new Date('2025-02-22'),
  },
  {
    id: 'p2',
    eventId: 'e1',
    volunteerId: 'v2',
    participationStatus: 'present',
    hoursAttended: 6,
    approvalStatus: 'approved',
    approvedBy: 'v1',
    approvedAt: new Date('2025-02-22'),
    feedback: null,
    registeredAt: new Date('2025-01-22'),
    updatedAt: new Date('2025-02-22'),
  },
  {
    id: 'p3',
    eventId: 'e1',
    volunteerId: 'v3',
    participationStatus: 'absent',
    hoursAttended: 0,
    approvalStatus: 'rejected',
    approvedBy: 'v1',
    approvedAt: new Date('2025-02-22'),
    feedback: 'Did not attend',
    registeredAt: new Date('2025-01-23'),
    updatedAt: new Date('2025-02-22'),
  },
  {
    id: 'p4',
    eventId: 'e2',
    volunteerId: 'v1',
    participationStatus: 'present',
    hoursAttended: 4,
    approvalStatus: 'approved',
    approvedBy: 'v1',
    approvedAt: new Date('2025-03-12'),
    feedback: null,
    registeredAt: new Date('2025-02-15'),
    updatedAt: new Date('2025-03-12'),
  },
  {
    id: 'p5',
    eventId: 'e2',
    volunteerId: 'v4',
    participationStatus: 'present',
    hoursAttended: 4,
    approvalStatus: 'approved',
    approvedBy: 'v1',
    approvedAt: new Date('2025-03-12'),
    feedback: null,
    registeredAt: new Date('2025-02-20'),
    updatedAt: new Date('2025-03-12'),
  },
  {
    id: 'p6',
    eventId: 'e2',
    volunteerId: 'v5',
    participationStatus: 'partially_present',
    hoursAttended: 2,
    approvalStatus: 'approved',
    approvedBy: 'v1',
    approvedAt: new Date('2025-03-12'),
    feedback: null,
    registeredAt: new Date('2025-02-18'),
    updatedAt: new Date('2025-03-12'),
  },
  {
    id: 'p7',
    eventId: 'e3',
    volunteerId: 'v2',
    participationStatus: 'present',
    hoursAttended: 5,
    approvalStatus: 'approved',
    approvedBy: 'v3',
    approvedAt: new Date('2025-04-24'),
    feedback: null,
    registeredAt: new Date('2025-04-01'),
    updatedAt: new Date('2025-04-24'),
  },
  {
    id: 'p8',
    eventId: 'e3',
    volunteerId: 'v6',
    participationStatus: 'present',
    hoursAttended: 5,
    approvalStatus: 'approved',
    approvedBy: 'v3',
    approvedAt: new Date('2025-04-24'),
    feedback: null,
    registeredAt: new Date('2025-04-05'),
    updatedAt: new Date('2025-04-24'),
  },
  {
    id: 'p9',
    eventId: 'e5',
    volunteerId: 'v1',
    participationStatus: 'present',
    hoursAttended: 56,
    approvalStatus: 'approved',
    approvedBy: 'v1',
    approvedAt: new Date('2025-06-10'),
    feedback: 'Outstanding leadership',
    registeredAt: new Date('2025-05-10'),
    updatedAt: new Date('2025-06-10'),
  },
  {
    id: 'p10',
    eventId: 'e5',
    volunteerId: 'v7',
    participationStatus: 'present',
    hoursAttended: 56,
    approvalStatus: 'approved',
    approvedBy: 'v1',
    approvedAt: new Date('2025-06-10'),
    feedback: null,
    registeredAt: new Date('2025-05-12'),
    updatedAt: new Date('2025-06-10'),
  },
  {
    id: 'p11',
    eventId: 'e8',
    volunteerId: 'v1',
    participationStatus: 'registered',
    hoursAttended: 0,
    approvalStatus: 'pending',
    approvedBy: null,
    approvedAt: null,
    feedback: null,
    registeredAt: new Date('2025-10-20'),
    updatedAt: new Date('2025-10-20'),
  },
  {
    id: 'p12',
    eventId: 'e8',
    volunteerId: 'v8',
    participationStatus: 'registered',
    hoursAttended: 0,
    approvalStatus: 'pending',
    approvedBy: null,
    approvedAt: null,
    feedback: null,
    registeredAt: new Date('2025-10-22'),
    updatedAt: new Date('2025-10-22'),
  },
  {
    id: 'p13',
    eventId: 'e9',
    volunteerId: 'v2',
    participationStatus: 'registered',
    hoursAttended: 0,
    approvalStatus: 'pending',
    approvedBy: null,
    approvedAt: null,
    feedback: null,
    registeredAt: new Date('2025-11-05'),
    updatedAt: new Date('2025-11-05'),
  },
  {
    id: 'p14',
    eventId: 'e9',
    volunteerId: 'v9',
    participationStatus: 'registered',
    hoursAttended: 0,
    approvalStatus: 'pending',
    approvedBy: null,
    approvedAt: null,
    feedback: null,
    registeredAt: new Date('2025-11-08'),
    updatedAt: new Date('2025-11-08'),
  },
  {
    id: 'p15',
    eventId: 'e10',
    volunteerId: 'v10',
    participationStatus: 'registered',
    hoursAttended: 0,
    approvalStatus: 'pending',
    approvedBy: null,
    approvedAt: null,
    feedback: null,
    registeredAt: new Date('2025-12-20'),
    updatedAt: new Date('2025-12-20'),
  },
]

export const mockParticipationsWithVolunteer: EventParticipationWithVolunteer[] =
  mockParticipations.map((p) => {
    const vol = mockVolunteers.find((v) => v.id === p.volunteerId)
    return {
      ...p,
      volunteer: vol,
      volunteerName: vol ? `${vol.firstName} ${vol.lastName}` : undefined,
    }
  })

export const mockParticipationsWithEvent: EventParticipationWithEvent[] = mockParticipations.map(
  (p) => {
    const evt = mockEvents.find((e) => e.id === p.eventId)
    return { ...p, event: evt, eventName: evt?.eventName, categoryName: undefined }
  }
)
