import type { RoleDefinition, UserRoleWithDefinition } from '@/types'

export const mockRoleDefinitions: RoleDefinition[] = [
  {
    id: 'rd1',
    roleName: 'admin',
    description: 'Full system access',
    hierarchyLevel: 0,
    permissions: { all: ['*'] },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'rd2',
    roleName: 'program_officer',
    description: 'Manage events and volunteers',
    hierarchyLevel: 1,
    permissions: { events: ['create', 'read', 'update', 'delete'], volunteers: ['read', 'update'] },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'rd3',
    roleName: 'event_lead',
    description: 'Lead event operations',
    hierarchyLevel: 2,
    permissions: { events: ['create', 'read', 'update'], attendance: ['create', 'read', 'update'] },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'rd4',
    roleName: 'documentation_lead',
    description: 'Manage documentation',
    hierarchyLevel: 3,
    permissions: { reports: ['read'], events: ['read'] },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'rd5',
    roleName: 'volunteer',
    description: 'Basic volunteer access',
    hierarchyLevel: 4,
    permissions: { events: ['read'], profile: ['read', 'update'] },
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
]

export const mockUserRolesWithDefinition: UserRoleWithDefinition[] = [
  {
    id: 'ur1',
    volunteerId: 'v1',
    roleDefinitionId: 'rd1',
    assignedBy: null,
    assignedAt: new Date('2024-01-01'),
    expiresAt: null,
    isActive: true,
    roleDefinition: mockRoleDefinitions[0],
  },
  {
    id: 'ur2',
    volunteerId: 'v3',
    roleDefinitionId: 'rd2',
    assignedBy: 'v1',
    assignedAt: new Date('2024-02-01'),
    expiresAt: null,
    isActive: true,
    roleDefinition: mockRoleDefinitions[1],
  },
  {
    id: 'ur3',
    volunteerId: 'v5',
    roleDefinitionId: 'rd3',
    assignedBy: 'v1',
    assignedAt: new Date('2024-03-01'),
    expiresAt: null,
    isActive: true,
    roleDefinition: mockRoleDefinitions[2],
  },
  {
    id: 'ur4',
    volunteerId: 'v14',
    roleDefinitionId: 'rd4',
    assignedBy: 'v1',
    assignedAt: new Date('2024-03-15'),
    expiresAt: null,
    isActive: true,
    roleDefinition: mockRoleDefinitions[3],
  },
  {
    id: 'ur5',
    volunteerId: 'v2',
    roleDefinitionId: 'rd5',
    assignedBy: null,
    assignedAt: new Date('2024-01-10'),
    expiresAt: null,
    isActive: true,
    roleDefinition: mockRoleDefinitions[4],
  },
]
