import type { Volunteer, VolunteerWithStats } from '@/types'

const base: Volunteer[] = [
  {
    id: 'v1',
    firstName: 'Aarav',
    lastName: 'Sharma',
    email: 'aarav@college.edu',
    rollNumber: 'CS2101',
    branch: 'Computer Science',
    year: 3,
    phoneNo: '9876543210',
    birthDate: '2003-05-15',
    gender: 'male',
    nssJoinYear: 2023,
    address: 'Mumbai',
    profilePic: null,
    isActive: true,
    authUserId: 'auth-1',
    createdAt: new Date('2023-08-01'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: 'v2',
    firstName: 'Priya',
    lastName: 'Patel',
    email: 'priya@college.edu',
    rollNumber: 'IT2205',
    branch: 'Information Technology',
    year: 2,
    phoneNo: '9876543211',
    birthDate: '2004-03-22',
    gender: 'female',
    nssJoinYear: 2024,
    address: 'Pune',
    profilePic: null,
    isActive: true,
    authUserId: 'auth-2',
    createdAt: new Date('2024-01-10'),
    updatedAt: new Date('2024-06-20'),
  },
  {
    id: 'v3',
    firstName: 'Rohan',
    lastName: 'Deshmukh',
    email: 'rohan@college.edu',
    rollNumber: 'ME2103',
    branch: 'Mechanical',
    year: 3,
    phoneNo: '9876543212',
    birthDate: '2003-11-08',
    gender: 'male',
    nssJoinYear: 2023,
    address: 'Nagpur',
    profilePic: null,
    isActive: true,
    authUserId: 'auth-3',
    createdAt: new Date('2023-08-05'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: 'v4',
    firstName: 'Sneha',
    lastName: 'Kulkarni',
    email: 'sneha@college.edu',
    rollNumber: 'EC2204',
    branch: 'Electronics',
    year: 2,
    phoneNo: '9876543213',
    birthDate: '2004-07-30',
    gender: 'female',
    nssJoinYear: 2024,
    address: 'Nashik',
    profilePic: null,
    isActive: true,
    authUserId: 'auth-4',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-05-18'),
  },
  {
    id: 'v5',
    firstName: 'Vikram',
    lastName: 'Joshi',
    email: 'vikram@college.edu',
    rollNumber: 'CS2102',
    branch: 'Computer Science',
    year: 3,
    phoneNo: '9876543214',
    birthDate: '2003-09-12',
    gender: 'male',
    nssJoinYear: 2023,
    address: 'Thane',
    profilePic: null,
    isActive: true,
    authUserId: 'auth-5',
    createdAt: new Date('2023-08-02'),
    updatedAt: new Date('2024-03-25'),
  },
  {
    id: 'v6',
    firstName: 'Ananya',
    lastName: 'Reddy',
    email: 'ananya@college.edu',
    rollNumber: 'CE2201',
    branch: 'Civil',
    year: 2,
    phoneNo: '9876543215',
    birthDate: '2004-01-18',
    gender: 'female',
    nssJoinYear: 2024,
    address: 'Hyderabad',
    profilePic: null,
    isActive: true,
    authUserId: 'auth-6',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-04-12'),
  },
  {
    id: 'v7',
    firstName: 'Arjun',
    lastName: 'Menon',
    email: 'arjun@college.edu',
    rollNumber: 'EE2103',
    branch: 'Electrical',
    year: 3,
    phoneNo: '9876543216',
    birthDate: '2003-04-25',
    gender: 'male',
    nssJoinYear: 2023,
    address: 'Kerala',
    profilePic: null,
    isActive: true,
    authUserId: 'auth-7',
    createdAt: new Date('2023-08-10'),
    updatedAt: new Date('2024-01-30'),
  },
  {
    id: 'v8',
    firstName: 'Kavya',
    lastName: 'Nair',
    email: 'kavya@college.edu',
    rollNumber: 'IT2206',
    branch: 'Information Technology',
    year: 2,
    phoneNo: '9876543217',
    birthDate: '2004-06-14',
    gender: 'female',
    nssJoinYear: 2024,
    address: 'Bangalore',
    profilePic: null,
    isActive: true,
    authUserId: 'auth-8',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-06-15'),
  },
  {
    id: 'v9',
    firstName: 'Rahul',
    lastName: 'Gupta',
    email: 'rahul@college.edu',
    rollNumber: 'CH2101',
    branch: 'Chemical',
    year: 3,
    phoneNo: '9876543218',
    birthDate: '2003-12-03',
    gender: 'male',
    nssJoinYear: 2023,
    address: 'Delhi',
    profilePic: null,
    isActive: true,
    authUserId: 'auth-9',
    createdAt: new Date('2023-08-15'),
    updatedAt: new Date('2024-02-28'),
  },
  {
    id: 'v10',
    firstName: 'Meera',
    lastName: 'Singh',
    email: 'meera@college.edu',
    rollNumber: 'CS2203',
    branch: 'Computer Science',
    year: 2,
    phoneNo: '9876543219',
    birthDate: '2004-10-20',
    gender: 'female',
    nssJoinYear: 2024,
    address: 'Jaipur',
    profilePic: null,
    isActive: true,
    authUserId: 'auth-10',
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-05-10'),
  },
  {
    id: 'v11',
    firstName: 'Aditya',
    lastName: 'Kumar',
    email: 'aditya@college.edu',
    rollNumber: 'ME2204',
    branch: 'Mechanical',
    year: 2,
    phoneNo: '9876543220',
    birthDate: '2004-08-07',
    gender: 'male',
    nssJoinYear: 2024,
    address: 'Lucknow',
    profilePic: null,
    isActive: true,
    authUserId: 'auth-11',
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-06-01'),
  },
  {
    id: 'v12',
    firstName: 'Ishita',
    lastName: 'Verma',
    email: 'ishita@college.edu',
    rollNumber: 'EC2105',
    branch: 'Electronics',
    year: 3,
    phoneNo: '9876543221',
    birthDate: '2003-02-28',
    gender: 'female',
    nssJoinYear: 2023,
    address: 'Chandigarh',
    profilePic: null,
    isActive: true,
    authUserId: 'auth-12',
    createdAt: new Date('2023-08-20'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 'v13',
    firstName: 'Dev',
    lastName: 'Chopra',
    email: 'dev@college.edu',
    rollNumber: 'CS2104',
    branch: 'Computer Science',
    year: 3,
    phoneNo: '9876543222',
    birthDate: '2003-06-19',
    gender: 'male',
    nssJoinYear: 2023,
    address: 'Kolkata',
    profilePic: null,
    isActive: true,
    authUserId: 'auth-13',
    createdAt: new Date('2023-08-25'),
    updatedAt: new Date('2024-04-20'),
  },
  {
    id: 'v14',
    firstName: 'Nisha',
    lastName: 'Agarwal',
    email: 'nisha@college.edu',
    rollNumber: 'IT2107',
    branch: 'Information Technology',
    year: 3,
    phoneNo: '9876543223',
    birthDate: '2003-10-11',
    gender: 'female',
    nssJoinYear: 2023,
    address: 'Ahmedabad',
    profilePic: null,
    isActive: true,
    authUserId: 'auth-14',
    createdAt: new Date('2023-09-01'),
    updatedAt: new Date('2024-05-05'),
  },
  {
    id: 'v15',
    firstName: 'Siddharth',
    lastName: 'Rao',
    email: 'siddharth@college.edu',
    rollNumber: 'CE2102',
    branch: 'Civil',
    year: 3,
    phoneNo: '9876543224',
    birthDate: '2003-01-25',
    gender: 'male',
    nssJoinYear: 2023,
    address: 'Chennai',
    profilePic: null,
    isActive: false,
    authUserId: 'auth-15',
    createdAt: new Date('2023-08-30'),
    updatedAt: new Date('2024-06-30'),
  },
]

export const mockVolunteers: Volunteer[] = base

export const mockVolunteersWithStats: VolunteerWithStats[] = base.map((v) => ({
  ...v,
  eventsParticipated: Math.floor(Math.random() * 12) + 1,
  totalHours: Math.floor(Math.random() * 80) + 10,
  approvedHours: Math.floor(Math.random() * 60) + 5,
  joinDate: v.createdAt.toISOString().split('T')[0],
}))
