'use client'

import { useEffect, useState } from 'react'
import { toast } from 'sonner'
import { FileText } from 'lucide-react'
import { getErrorMessage } from '@/lib/error-utils'
import { PageHeader } from '@/components/page-header'
import { EmptyState } from '@/components/empty-state'
import { Skeleton } from '@/components/ui/skeleton'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { getGeneratedReports, type GeneratedReportEntry } from '@/app/actions/reports'

function formatDateTime(iso: string): string {
  const d = new Date(iso)
  return d.toLocaleString(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  })
}

export function ReportDocsPage() {
  const [rows, setRows] = useState<GeneratedReportEntry[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    let ignore = false
    async function load() {
      try {
        const data = await getGeneratedReports()
        if (!ignore) setRows(data)
      } catch (err) {
        if (!ignore) toast.error(getErrorMessage(err, 'Failed to load report history'))
      } finally {
        if (!ignore) setLoading(false)
      }
    }
    load()
    return () => {
      ignore = true
    }
  }, [])

  return (
    <div className="space-y-6">
      <PageHeader
        title="Report Docs"
        description="History of NSS reports generated from the attendance manager."
      />

      {loading ? (
        <div className="space-y-3">
          {Array.from({ length: 5 }).map((_, i) => (
            <Skeleton key={i} className="h-12 w-full" />
          ))}
        </div>
      ) : rows.length === 0 ? (
        <EmptyState
          icon={FileText}
          title="No reports generated yet"
          description="Mark attendance for an event, then use Generate Report to create one."
        />
      ) : (
        <div className="rounded-md border">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Event</TableHead>
                <TableHead>Generated By</TableHead>
                <TableHead>Filename</TableHead>
                <TableHead className="text-right">Attendees</TableHead>
                <TableHead>When</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {rows.map((r) => (
                <TableRow key={r.id}>
                  <TableCell className="font-medium">
                    {r.eventName ?? <span className="text-muted-foreground">(deleted event)</span>}
                    {r.objective && (
                      <div className="text-muted-foreground mt-0.5 line-clamp-1 text-xs">
                        {r.objective}
                      </div>
                    )}
                  </TableCell>
                  <TableCell className="text-muted-foreground">{r.actorName ?? '—'}</TableCell>
                  <TableCell className="text-muted-foreground font-mono text-xs">
                    {r.filename ?? '—'}
                  </TableCell>
                  <TableCell className="text-muted-foreground text-right">
                    {r.attendeeCount ?? '—'}
                  </TableCell>
                  <TableCell className="text-muted-foreground text-xs">
                    {formatDateTime(r.createdAt)}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>
      )}
    </div>
  )
}
